Repository hiro-o918/awsctx, pull requests merged in 2022-03, with the labels that each got.

#16 fix: call use_context in the use_context_interactive
  src/aws.rs
Labels: bug

#18 Implement auto completion for awsctx
  Cargo.lock
  Cargo.toml
  README.md
  src/aws.rs
  src/creds.rs
  src/main.rs
Labels: feature

#19 ignore profiles which is not selected
  Cargo.lock
  Cargo.toml
  src/aws.rs
  src/creds.rs
  src/ctx.rs
  src/main.rs
Labels: bug

#29 fix homebrew release workflow
  .github/workflows/homebrew-release.yml
  Cargo.toml
Labels: chore

#30 fix getting tags
  .github/workflows/homebrew-release.yml
Labels: chore
